JetCloud/Pages/Index.cshtml.cs
using JetCloud.Data;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using System.IO.Compression;
using System.IO;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.StaticFiles;
using System.Diagnostics.Tracing;
using System;
using System.Security.Cryptography.Pkcs;
using Microsoft.Data.SqlClient;
using System.Diagnostics.Eventing.Reader;
using Microsoft.AspNetCore.Authorization;
using static System.Net.WebRequestMethods;
using System.Text;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json.Linq;
using static System.Net.Mime.MediaTypeNames;
using System.Security.Claims;

namespace JetCloud.Pages
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private AppDbContext _db;
        private IWebHostEnvironment _he;

        public Files uploadedFile = new Files();

        [BindProperty]
        public IFormFile Upload { get; set; }

        public IList<Files> DepartmentFiles { get; set; }
        public IList<Department> Departments { get; set; }
        public IList<Users> Users { get; set; }
        public string CurrentFilter { get; set; }
        public string DepartmentSort { get; set; }
        public string CurrentDepartment { get; set; }
        public string CurrentUser { get; set; }

        IDataProtector _protector;

        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public IndexModel(AppDbContext db, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> um, IWebHostEnvironment he, IDataProtectionProvider provider)
        {
            _signInManager = signInManager;
            _userManager = um;
            _db = db;
            _he = he;
            _protector = provider.CreateProtector("Contoso.Security.BearerToken");

        }
        //Start of Adapted Code (Tdykstra, n.d.)

        public async Task OnGetAsync(string sortOrder, string search, int? depID)
        {

            var currentUser = User.FindFirstValue(ClaimTypes.Email);
            var currentAspUser = await _userManager.FindByEmailAsync(currentUser);
            var currentRoles = await _userManager.GetRolesAsync(currentAspUser);
            var assingedRole = currentRoles[0];


            foreach (var user in _db.Users)
            {
                string decryptedString = _protector.Unprotect(user.Email);
                if (decryptedString == currentUser){
                    CurrentUser = user.Title + " " + user.GivenName  + " " + user.SurName;
                    if (assingedRole != "Admin")
                    {
                        depID = user.DepartmentID;
                    }
                }
            }
              
            DepartmentSort = String.IsNullOrEmpty(sortOrder) ? "dep_sort" : "";

            if (depID == null){
                depID = 0;
            }
           
            CurrentFilter = search;

            foreach (var dep in _db.Departments)
            {
                if (dep.departmentID == depID)
                {
                    var currentDepName = dep.departmentName;
                    CurrentDepartment = Convert.ToString(currentDepName);
                }
            }
            IQueryable <Files> depFiles = from f in _db.DepartmentFiles select f;

            if (!string.IsNullOrEmpty(search))
            {
                depFiles = depFiles.Where(b => b.fileName.Contains(search));
            }
            if (assingedRole != "Admin")
            {
                depFiles = depFiles.Where(b => b.departmentID == depID);
            }
            else
            {
                switch (sortOrder)
                {
                    case "dep_sort":
                        depFiles = depFiles.Where(b => b.departmentID == depID);
                        break;
                    default:
                        depFiles = depFiles.OrderBy(b => b.departmentID);
                        break;
                }
            }
            DepartmentFiles = await depFiles.ToListAsync();
            Departments = await _db.Departments.ToListAsync();
            Users = await _db.Users.OrderByDescending(b => b.UserID).ToListAsync();
        }

        //end of adapted Code

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {

                return Page();
            }

            var currentFile = _db.DepartmentFiles.OrderByDescending(b => b.fileID).FirstOrDefault();
            var currentUser = User.FindFirstValue(ClaimTypes.Email);
            var currentAspUser = await _userManager.FindByEmailAsync(currentUser);
            var currentRoles = await _userManager.GetRolesAsync(currentAspUser);
            var assingedRole = currentRoles[0];

            if (currentFile == null)
            {
                uploadedFile.fileID = 1;
                uploadedFile.fileVersion = 1;
            }
            else
            {
                int fileID = currentFile.fileID + 1;
                uploadedFile.fileID = fileID;
            }
            uploadedFile.fileName = Convert.ToString(Upload.FileName);
            
            if (assingedRole == "Admin")
            {
                uploadedFile.departmentID = Convert.ToInt32(Request.Form["departmentID"]);
            }
            else {
                foreach (var user in _db.Users)
                {
                    string decryptedString = _protector.Unprotect(user.Email);
                    if (decryptedString == currentUser)
                    {
                        uploadedFile.departmentID = user.DepartmentID;
                    }
                }
               
            }
            uploadedFile.fileDate = DateTime.Now;
            uploadedFile.fileVersion = 1;

            //This was just testing other methods, will switch to appropriate type from download function
            var filePath = Path.Combine(_he.ContentRootPath, "uploads", Upload.FileName);
            //uploadedFile.fileType = _protector.Protect(Convert.ToString(filePath));
            uploadedFile.fileType = Convert.ToString(filePath);
            //end of method testing

            using (MemoryStream ms = new MemoryStream(100))
            {
                await Upload.CopyToAsync(ms);
                uploadedFile.fileData = ms.ToArray();
            }
            _db.DepartmentFiles.Add(uploadedFile);
            await _db.SaveChangesAsync();
            return RedirectToPage("Index");
        }

        public async Task<IActionResult> OnPostDownloadAsync(int fileID)
        {
           
            var downloadFile = await _db.DepartmentFiles.FindAsync(fileID);               

            if (!(downloadFile == null))
            {
                //start of adapted code from (Khan, n.d.)
                byte[] bytes = downloadFile.fileData;
                string contentType = "";
                new FileExtensionContentTypeProvider().TryGetContentType(downloadFile.fileName, out contentType);
                //end of adapted code

                //start of adatped code (Halasz, 2020)
                return new FileContentResult(bytes, contentType) { FileDownloadName = downloadFile.fileName };
                //end of adapted code
            }
            else
            {
                return RedirectToPage("/Index");
            }
        }
        public async Task<IActionResult> OnPostDownloadAllAsync()
        {
            //Start of adapted Code (Zhi, 2022)
           
            var fileCapacity = await _db.DepartmentFiles.ToListAsync();
            var zipName = $"JetClouds-{DateTime.Now.ToString("yyyy_MM_dd")}.zip";
            if (fileCapacity != null) {
                using (var ms = new MemoryStream())
                {
                    using (var zip = new ZipArchive(ms, ZipArchiveMode.Create, true))
                    {
                        foreach (var file in _db.DepartmentFiles)
                        {
                            var entry = zip.CreateEntry(file.fileName);
                            using (var fs = new MemoryStream(file.fileData))
                            using (var es = entry.Open())
                            {
                                fs.CopyTo(es);
                            }

                        }
                    }
                    return File(ms.ToArray(), "JetClouds/Zip", zipName);
                }

            }
            //end of Adapted Code

            return RedirectToPage("/Index");
        }
        public async Task<IActionResult> OnPostExcelAsync()
        {
            //Start of adapted code from (Ardal, 2020)
            var fileCapacity = await _db.DepartmentFiles.ToListAsync();

            var builder = new StringBuilder();
            builder.AppendLine("fileName,fileDate,fileType,fileData,fileVersion,departmentID,fileID");

            if (fileCapacity != null){
                foreach (var file in _db.DepartmentFiles)
                {
                    builder.AppendLine($"{file.fileName},{file.fileDate},{file.fileType},{file.fileData},{file.fileVersion},{file.departmentID},{file.fileID}");
                }
                return File(Encoding.UTF8.GetBytes(builder.ToString()), "text/csv", "JetCloudFiles.csv");
            }      
            return RedirectToPage("/Index");
            //end of adapted code
        }
        public async Task<IActionResult> OnPostDeleteAsync(int? fileID)
        {
            if(fileID == null)
            {
                return NotFound();
            }
            var file = await _db.DepartmentFiles.FindAsync(fileID);
           

JetCloud/Pages/Login.cshtml.cs
using JetCloud.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace JetCloud.Pages
{
    public class LoginModel : PageModel
    {
        [BindProperty]
        public Login Input { get; set; }

        private readonly SignInManager<ApplicationUser> _signInManager;

        public LoginModel(SignInManager<ApplicationUser> signInManager)
        {
            _signInManager = signInManager;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, false, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    return RedirectToPage("/Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return Page();
                }
            }
            return Page();
        }
    }
}

JetCloud/Pages/Logout.cshtml.cs
using JetCloud.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace JetCloud.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> _signInManager;

        public LogoutModel(SignInManager<ApplicationUser> signInManager)
        {
            _signInManager = signInManager;
        }
        public async Task<IActionResult> OnPost()
        {
            await _signInManager.SignOutAsync();
            return RedirectToPage("/Index");
        }

    }
}

JetCloud/Pages/Register.cshtml.cs
using JetCloud.Data;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Reflection;
using System.Reflection.Metadata;

namespace JetCloud.Pages
{
    public class RegisterModel : PageModel
    {
        [BindProperty]
        public Registration Input { get; set; }

        IDataProtector _protector;

        private AppDbContext _db;

        public Users newUser = new Users();

        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private RoleManager<IdentityRole> _roleManager;

        public RegisterModel(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> um, SignInManager<ApplicationUser> sm, AppDbContext db, IDataProtectionProvider provider)
        {
            _signInManager = sm;
            _userManager = um;
            _db = db;
            _protector = provider.CreateProtector("Contoso.Security.BearerToken");
            _roleManager = roleManager;
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = Input.UserName, Email = Input.Email };
                var result = await _userManager.CreateAsync(user, Input.Password);
                if (result.Succeeded)
                {
                    //await CreateRoles();
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    await _userManager.AddToRoleAsync(user, "Member");
                    var currentUsers = _db.Users.OrderByDescending(b => b.UserID).FirstOrDefault();

                    if (currentUsers == null)
                    {
                        newUser.UserID = 1;
                    }
                    else
                    {
                        newUser.UserID = currentUsers.UserID + 1;
                    }
                    newUser.Email = _protector.Protect(Input.Email);
                    newUser.GivenName = Convert.ToString(Request.Form["GivenName"]);
                    newUser.SurName = Convert.ToString(Request.Form["SurName"]);
                    newUser.Title = Convert.ToString(Request.Form["Title"]);
                    newUser.DepartmentID = Convert.ToInt32(Request.Form["DepartmentID"]);
                    newUser.SubscriptionStatus = true;
                    newUser.Dob = Convert.ToDateTime(Request.Form["Dob"]);
                    _db.Users.Add(newUser);
                    await _db.SaveChangesAsync();
                    return RedirectToPage("/Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
                return Page();
        }
        private async Task CreateRoles()
        {
            String[] roleNames = { "Admin", "Member" };
            foreach (var roleName in roleNames)
            {
                var roleExists = await _roleManager.RoleExistsAsync(roleName);
                if (!roleExists)
                {
                    var roleResult = await _roleManager.CreateAsync(new IdentityRole(roleName));
                }
            }
            var _user = await _userManager.FindByNameAsync("peter@chester.ac.uk");
            if (_user != null)
            {
                await _userManager.AddToRoleAsync(_user, "Admin");
            }
        }

    }
}

JetCloud/Pages/Index.cshtml
@page
@inject Microsoft.AspNetCore.Hosting.IWebHostEnvironment hostingEnv
@model IndexModel
@{
    ViewData["Title"] = "Dashboard";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using Microsoft.AspNetCore.Identity
@using JetCloud.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@*Start of Dapated Code from (Google, 2019)*@
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,400,0,0" />
@*End of Adapted Code*@
        <form id="searchBarContainer" asp-page="./Index" method="get">
            <input id="inputText" type="text" name="Search" value="@Model.CurrentFilter" placeholder="Search"/>
            <button id="submitSearch" type="submit"><i class="material-symbols-rounded">search</i></button>
            <a asp-page="./Index">Reset</a>
        </form>

<div id="toolBar">
    <button id="tools" onclick="showForm_hideForm()">
        <div id="icon"><i class="material-symbols-rounded">publish</i></div>
        <div id="iconTitle">Upload</div>
    </button>
    @if (SignInManager.IsSignedIn(User))
    {
        if (User.IsInRole("Admin"))
        {
     <form method="post" asp-page-handler="DownloadAll">
        <button id="tools" asp-page-handler="DownloadAll">
            <div id="icon"><i class="material-symbols-rounded">download</i></div>
            <div id="iconTitle">Download</div>
        </button>
    </form>

        <form method="post" asp-page-handler="Excel">
            <button id="tools" asp-page-handler="Excel">
            <div id="icon"><i class="material-symbols-rounded">cloud_download</i></div>
            <div id="iconTitle">ExportCSV</div>
            </button>
        </form>
     }
   }
</div>
        <div id="currentFiles">
            <p>@Model.CurrentDepartment Files</p>
        </div>
        <div id="filesGrid">
         
                @foreach (var file in Model.DepartmentFiles)
                {

            <div id="departmentFiles">

            <div id="fileDropDown">
                <i class="material-symbols-rounded">more_vert</i>
                <div id="fileLinks" >
                    <form method="post" asp-page-handler="Download" asp-route-fileID="@file.fileID">
                        <button type="submit" asp-page-handler="Download" asp-route-fileID="@file.fileID">Download</button>
                    </form>
                   @if (SignInManager.IsSignedIn(User))
                    {
                        if (User.IsInRole("Admin"))
                        {
                            <form method="post" asp-page-handler="Delete" asp-route-fileID="@file.fileID">
                                <button type="submit" asp-page-handler="Delete" asp-route-fileID="@file.fileID">Delete</button>
                            </form>
                        }
                    }
                </div>
            </div>

               
                <div id="fileBanner">
                    <p>@file.fileName</p>
                    <p>Last Edit: @file.fileDate</p>
                    <p>Version: @file.fileVersion</p>
                </div>
            </div>

                }

       
        </div>
    <div id="sideBar">

        <div id="departments">
            <div id="subHeading">
                <h4>Squadron</h4>
                <div id="moreDiv" onclick="show_hide()">
                    <i class="material-symbols-rounded">more_vert</i>
                    <div id="links">
                        <a>Create</a>
                        <a>Edit</a>
                        <a>Delete</a>
                    </div>
                </div>
            </div>
            @if (SignInManager.IsSignedIn(User))
            {
            if (User.IsInRole("Admin"))
            {
                @foreach (var deps in Model.Departments)
                {
                    <a asp-page="./Index" asp-route-depID="@deps.departmentID" asp-route-sortOrder="dep_sort">
                        <p>@deps.departmentName : @deps.departmentID</p>
                    </a>
                }
            }
            else
            {
                <a><p>@Model.CurrentDepartment </p></a>
            }
            }


        </div>
    
        <div id ="users">
            <div id="subHeading">
            <h4>Pilot</h4>
            </div>
            @if (SignInManager.IsSignedIn(User))
            {
                if (User.IsInRole("Admin"))
                {
                    @foreach (var user in Model.Users)
                    {
                    <p>@user.Title @user.GivenName @user.SurName </p>
                    }
                }
                else
                {
                    <p>@Model.CurrentUser </p>
                }
            }  
        </div>
        <div id="subHeading">
            <h4>Storage</h4>
        </div>
    </div>
<div id="uploadFileForm"> 
        <button id="closeBtn" onclick="showForm_hideForm()"><i class="material-symbols-rounded">close</i></button>
    <div id="welcomeMessage">
        <img src="~/img/JetCloudsLogoSolo.png" alt="logo">
    </div>
        <form id="uploadFile" enctype="multipart/form-data" method="post">

        @if (SignInManager.IsSignedIn(User))
        {
          if (User.IsInRole("Admin"))
          {
            <label>Select Department</label>
            <input id="FormInputs" asp-for="uploadedFile.departmentID" name="departmentID" placeholder="DepartmentID" />
            <span asp-validation-for="uploadedFile.departmentID"></span>
          }
            <input id="FormInputs" type="file" id="file1" asp-for="Upload" multiple="multiple" />
            <input id="uploadFilebtn" type="submit">
            }
    </form>
</div>




   

JetCloud/Pages/Login.cshtml
@page
@model LoginModel
@{
    ViewData["Title"] = "Login";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<form id="LoginForm" method="post">
    <div id="welcomeMessage">
        <img src="~/img/JetCloudsLogoSolo.png" alt="logo">
    </div>
    <div asp-validation-summary="All"></div>

    <input id="FormInputs" type="text" asp-for="Input.Email" placeholder="Email" />
    <span asp-validation-for="Input.Email"></span>

    <input id="FormInputs" type="password" asp-for="Input.Password" placeholder="Password" />
    <span asp-validation-for="Input.Password"></span>

    <div id="formActions">
        <button id="loginSubmitBtn" type="submit">LOGIN</button>
    </div>
    <div id="RegisterText">
        <p5>Don't have an account? <a asp-page="/Register">Register Here</a></p5>
    </div>


</form>

JetCloud/Pages/Logout.cshtml
@page
@model JetCloud.Pages.LogoutModel
@{
}

JetCloud/Pages/Register.cshtml
@page
@model RegisterModel
@{
    ViewData["Title"] = "Register";
    //Layout = "~/Pages/_Layout.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using JetCloud.Data
@using Microsoft.Extensions.Options

<form id="RegisterForm" asp-action="Register" class="RegisterForm" method="post">
    <div id="welcomeMessage">
        <h4>Registration Details</h4>
    </div>
    

    <label id="FormLabels" asp-for="newUser.GivenName"></label>
    <input id="RegisterInputs" type="text" asp-for="newUser.GivenName" name="GivenName" placeholder="GivenName" />
    
    <label id="FormLabels" asp-for="newUser.SurName"></label>
    <input id="RegisterInputs" type="text" asp-for="newUser.SurName" name="SurName" placeholder="SurName" />


    <label id="FormLabels" asp-for="newUser.Title"></label>
    <input id="RegisterInputs" type="text" asp-for=" newUser.Title" name="Title" placeholder="Title" />
      
  
    <label id="FormLabels" asp-for="newUser.Dob">Date of Birth</label>
    <input id="RegisterInputs" asp-for="newUser.Dob" name="Dob" />
       

    <label id="FormLabels" asp-for="newUser.DepartmentID"></label>
    <input id="RegisterInputs" asp-for="newUser.DepartmentID" name="DepartmentID" />
      

    <label id="FormLabels" asp-for="Input.Email"></label>
    <input id="RegisterInputs" asp-for="Input.Email" />
    <span asp-validation-for="Input.Email"></span>

    <label id="FormLabels" asp-for="Input.UserName"></label>
    <input id="RegisterInputs" asp-for="Input.UserName" />
    <span asp-validation-for="Input.UserName"></span>

    <label id="FormLabels" asp-for="Input.Password"></label>
    <input id="RegisterInputs" asp-for="Input.Password" />
    <span asp-validation-for="Input.Password"></span>

    <label id="FormLabels" asp-for="Input.ConfirmPassword"></label>
    <input id="RegisterInputs" asp-for="Input.ConfirmPassword" />
    <span asp-validation-for="Input.ConfirmPassword"></span>
 
    <button id="RegisterBtn" type="submit">Register</button>
</form>